import { Ingredient, Dish, DishIngredient, db } from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(Ingredient).values([
    { id: 1, name: "Large Leek", strength: 185 },
    { id: 2, name: "Tasty Mushroom", strength: 167 },
    { id: 3, name: "Fancy Egg", strength: 115 },
    { id: 4, name: "Soft Potato", strength: 124 },
    { id: 5, name: "Fancy Apple", strength: 90 },
    { id: 6, name: "Fiery Herb", strength: 130 },
    { id: 7, name: "Bean Sausage", strength: 103 },
    { id: 8, name: "Moomoo Milk", strength: 98 },
    { id: 9, name: "Honey", strength: 101 },
    { id: 10, name: "Pure Oil", strength: 121 },
    { id: 11, name: "Warming Ginger", strength: 109 },
    { id: 12, name: "Snoozy Tomato", strength: 110 },
    { id: 13, name: "Soothing Cacao", strength: 151 },
    { id: 14, name: "Slowpoke Tail", strength: 342 },
    { id: 15, name: "Greengrass Soybeans", strength: 100 },
    { id: 16, name: "Greengrass Corn", strength: 1400 },
  ]);

  await db.insert(Dish).values([
    {
      id: 1,
      type: "curry",
      name: "Mixed Curry",
      baseStrength: 0,
      minPotSize: 0,
    },
    {
      id: 2,
      type: "curry",
      name: "Fancy Apple Curry",
      baseStrength: 668,
      minPotSize: 7,
    },
    {
      id: 3,
      type: "curry",
      name: "Grilled Tail Curry",
      baseStrength: 7483,
      minPotSize: 33,
    },
    {
      id: 4,
      type: "curry",
      name: "Solar Power Tomato Curry",
      baseStrength: 1943,
      minPotSize: 15,
    },
    {
      id: 5,
      type: "curry",
      name: "Dream Eater Butter Curry",
      baseStrength: 9010,
      minPotSize: 55,
    },
    {
      id: 6,
      type: "curry",
      name: "Spicy Leek Curry",
      baseStrength: 5900,
      minPotSize: 32,
    },
    {
      id: 7,
      type: "curry",
      name: "Spore Mushroom Curry",
      baseStrength: 4041,
      minPotSize: 23,
    },
    {
      id: 8,
      type: "curry",
      name: "Egg Bomb Curry",
      baseStrength: 4523,
      minPotSize: 35,
    },
    {
      id: 9,
      type: "curry",
      name: "Hearty Cheeseburger Curry",
      baseStrength: 1785,
      minPotSize: 16,
    },
    {
      id: 10,
      type: "curry",
      name: "Soft Potato Chowder",
      baseStrength: 3089,
      minPotSize: 22,
    },
    {
      id: 11,
      type: "curry",
      name: "Simple Chowder",
      baseStrength: 727,
      minPotSize: 7,
    },
    {
      id: 12,
      type: "curry",
      name: "Beanburger Curry",
      baseStrength: 764,
      minPotSize: 7,
    },
    {
      id: 13,
      type: "curry",
      name: "Mild Honey Curry",
      baseStrength: 749,
      minPotSize: 7,
    },
    {
      id: 14,
      type: "curry",
      name: "Ninja Curry",
      baseStrength: 6159,
      minPotSize: 38,
    },
    {
      id: 15,
      type: "curry",
      name: "Drought Katsu Curry",
      baseStrength: 1881,
      minPotSize: 15,
    },
    {
      id: 16,
      type: "curry",
      name: "Melty Omelette Curry",
      baseStrength: 2009,
      minPotSize: 16,
    },
    {
      id: 17,
      type: "curry",
      name: "Bulk Up Bean Curry",
      baseStrength: 3274,
      minPotSize: 26,
    },
    {
      id: 18,
      type: "curry",
      name: "Limber Corn Stew",
      baseStrength: 4670,
      minPotSize: 30,
    },
    {
      id: 19,
      type: "curry",
      name: "Inferno Corn Keema Curry",
      baseStrength: 13690,
      minPotSize: 77,
    },
    {
      id: 20,
      type: "salad",
      name: "Mixed Salad",
      baseStrength: 0,
      minPotSize: 0,
    },
    {
      id: 21,
      type: "salad",
      name: "Slowpoke Tail Pepper Salad",
      baseStrength: 8169,
      minPotSize: 35,
    },
    {
      id: 22,
      type: "salad",
      name: "Spore Mushroom Salad",
      baseStrength: 5858,
      minPotSize: 33,
    },
    {
      id: 23,
      type: "salad",
      name: "Snow Cloak Caesar Salad",
      baseStrength: 1774,
      minPotSize: 16,
    },
    {
      id: 24,
      type: "salad",
      name: "Gluttony Potato Salad",
      baseStrength: 5040,
      minPotSize: 36,
    },
    {
      id: 25,
      type: "salad",
      name: "Water Veil Tofu Salad",
      baseStrength: 1843,
      minPotSize: 16,
    },
    {
      id: 26,
      type: "salad",
      name: "Superpower Extreme Salad",
      baseStrength: 2958,
      minPotSize: 23,
    },
    {
      id: 27,
      type: "salad",
      name: "Bean Ham Salad",
      baseStrength: 873,
      minPotSize: 8,
    },
    {
      id: 28,
      type: "salad",
      name: "Snoozy Tomato Salad",
      baseStrength: 933,
      minPotSize: 8,
    },
    {
      id: 29,
      type: "salad",
      name: "Moomoo Caprese Salad",
      baseStrength: 2856,
      minPotSize: 23,
    },
    {
      id: 30,
      type: "salad",
      name: "Contrary Chocolate Meat Salad",
      baseStrength: 3558,
      minPotSize: 23,
    },
    {
      id: 31,
      type: "salad",
      name: "Overheat Ginger Salad",
      baseStrength: 5225,
      minPotSize: 35,
    },
    {
      id: 32,
      type: "salad",
      name: "Fancy Apple Salad",
      baseStrength: 763,
      minPotSize: 8,
    },
    {
      id: 33,
      type: "salad",
      name: "Immunity Leek Salad",
      baseStrength: 2658,
      minPotSize: 15,
    },
    {
      id: 34,
      type: "salad",
      name: "Dazzling Apple Cheese Salad",
      baseStrength: 2578,
      minPotSize: 23,
    },
    {
      id: 35,
      type: "salad",
      name: "Ninja Salad",
      baseStrength: 10095,
      minPotSize: 53,
    },
    {
      id: 36,
      type: "salad",
      name: "Heat Wave Tofu Salad",
      baseStrength: 1976,
      minPotSize: 16,
    },
    {
      id: 37,
      type: "salad",
      name: "Greengrass Salad",
      baseStrength: 11393,
      minPotSize: 62,
    },
    {
      id: 38,
      type: "salad",
      name: "Calm Mind Fruit Salad",
      baseStrength: 7675,
      minPotSize: 49,
    },
    {
      id: 39,
      type: "salad",
      name: "Fury Attack Corn Salad",
      baseStrength: 2785,
      minPotSize: 17,
    },
    {
      id: 40,
      type: "dessert",
      name: "Mixed Juice",
      baseStrength: 0,
      minPotSize: 0,
    },
    {
      id: 41,
      type: "dessert",
      name: "Fluffy Sweet Potatoes",
      baseStrength: 1783,
      minPotSize: 14,
    },
    {
      id: 42,
      type: "dessert",
      name: "Steadfast Ginger Cookies",
      baseStrength: 4921,
      minPotSize: 35,
    },
    {
      id: 43,
      type: "dessert",
      name: "Fancy Apple Juice",
      baseStrength: 763,
      minPotSize: 8,
    },
    {
      id: 44,
      type: "dessert",
      name: "Craft Soda Pop",
      baseStrength: 964,
      minPotSize: 9,
    },
    {
      id: 45,
      type: "dessert",
      name: "Ember Ginger Tea",
      baseStrength: 1788,
      minPotSize: 16,
    },
    {
      id: 46,
      type: "dessert",
      name: "Jigglypuff's Fruity Flan",
      baseStrength: 7594,
      minPotSize: 55,
    },
    {
      id: 47,
      type: "dessert",
      name: "Lovely Kiss Smoothie",
      baseStrength: 4734,
      minPotSize: 35,
    },
    {
      id: 48,
      type: "dessert",
      name: "Lucky Chant Apple Pie",
      baseStrength: 1634,
      minPotSize: 16,
    },
    {
      id: 49,
      type: "dessert",
      name: "Neroli's Restorative Tea",
      baseStrength: 5065,
      minPotSize: 35,
    },
    {
      id: 50,
      type: "dessert",
      name: "Sweet Scent Chocolate Cake",
      baseStrength: 3280,
      minPotSize: 24,
    },
    {
      id: 51,
      type: "dessert",
      name: "Warm Moomoo Milk",
      baseStrength: 727,
      minPotSize: 7,
    },
    {
      id: 52,
      type: "dessert",
      name: "Cloud Nine Soy Cake",
      baseStrength: 1798,
      minPotSize: 15,
    },
    {
      id: 53,
      type: "dessert",
      name: "Hustle Protein Smoothie",
      baseStrength: 3168,
      minPotSize: 23,
    },
    {
      id: 54,
      type: "dessert",
      name: "Stalwart Vegetable Juice",
      baseStrength: 1798,
      minPotSize: 16,
    },
    {
      id: 55,
      type: "dessert",
      name: "Big Malasada",
      baseStrength: 2927,
      minPotSize: 23,
    },
    {
      id: 56,
      type: "dessert",
      name: "Huge Power Soy Donuts",
      baseStrength: 3213,
      minPotSize: 22,
    },
    {
      id: 57,
      type: "dessert",
      name: "Explosion Popcorn",
      baseStrength: 6048,
      minPotSize: 36,
    },
    {
      id: 58,
      type: "dessert",
      name: "Teatime Corn Scones",
      baseStrength: 10925,
      minPotSize: 67,
    },
    {
      id: 59,
      type: "dessert",
      name: "Petal Dance Chocalate Tart",
      baseStrength: 3314,
      minPotSize: 22,
    },
    {
      id: 60,
      type: "dessert",
      name: "Flower Gift Macarons",
      baseStrength: 13834,
      minPotSize: 77,
    },
  ]);

  await db.insert(DishIngredient).values([
    { dishId: 1, ingredientId: 1, quantity: 0 },
    { dishId: 1, ingredientId: 2, quantity: 0 },
    { dishId: 1, ingredientId: 3, quantity: 0 },
    { dishId: 1, ingredientId: 4, quantity: 0 },
    { dishId: 1, ingredientId: 5, quantity: 0 },
    { dishId: 1, ingredientId: 6, quantity: 0 },
    { dishId: 1, ingredientId: 7, quantity: 0 },
    { dishId: 1, ingredientId: 8, quantity: 0 },
    { dishId: 1, ingredientId: 9, quantity: 0 },
    { dishId: 1, ingredientId: 10, quantity: 0 },
    { dishId: 1, ingredientId: 11, quantity: 0 },
    { dishId: 1, ingredientId: 12, quantity: 0 },
    { dishId: 1, ingredientId: 13, quantity: 0 },
    { dishId: 1, ingredientId: 14, quantity: 0 },
    { dishId: 1, ingredientId: 15, quantity: 0 },
    { dishId: 1, ingredientId: 16, quantity: 0 },
    { dishId: 2, ingredientId: 1, quantity: 0 },
    { dishId: 2, ingredientId: 2, quantity: 0 },
    { dishId: 2, ingredientId: 3, quantity: 0 },
    { dishId: 2, ingredientId: 4, quantity: 0 },
    { dishId: 2, ingredientId: 5, quantity: 7 },
    { dishId: 2, ingredientId: 6, quantity: 0 },
    { dishId: 2, ingredientId: 7, quantity: 0 },
    { dishId: 2, ingredientId: 8, quantity: 0 },
    { dishId: 2, ingredientId: 9, quantity: 0 },
    { dishId: 2, ingredientId: 10, quantity: 0 },
    { dishId: 2, ingredientId: 11, quantity: 0 },
    { dishId: 2, ingredientId: 12, quantity: 0 },
    { dishId: 2, ingredientId: 13, quantity: 0 },
    { dishId: 2, ingredientId: 14, quantity: 0 },
    { dishId: 2, ingredientId: 15, quantity: 0 },
    { dishId: 2, ingredientId: 16, quantity: 0 },
    { dishId: 3, ingredientId: 1, quantity: 0 },
    { dishId: 3, ingredientId: 2, quantity: 0 },
    { dishId: 3, ingredientId: 3, quantity: 0 },
    { dishId: 3, ingredientId: 4, quantity: 0 },
    { dishId: 3, ingredientId: 5, quantity: 0 },
    { dishId: 3, ingredientId: 6, quantity: 25 },
    { dishId: 3, ingredientId: 7, quantity: 0 },
    { dishId: 3, ingredientId: 8, quantity: 0 },
    { dishId: 3, ingredientId: 9, quantity: 0 },
    { dishId: 3, ingredientId: 10, quantity: 0 },
    { dishId: 3, ingredientId: 11, quantity: 0 },
    { dishId: 3, ingredientId: 12, quantity: 0 },
    { dishId: 3, ingredientId: 13, quantity: 0 },
    { dishId: 3, ingredientId: 14, quantity: 8 },
    { dishId: 3, ingredientId: 15, quantity: 0 },
    { dishId: 3, ingredientId: 16, quantity: 0 },
    { dishId: 4, ingredientId: 1, quantity: 0 },
    { dishId: 4, ingredientId: 2, quantity: 0 },
    { dishId: 4, ingredientId: 3, quantity: 0 },
    { dishId: 4, ingredientId: 4, quantity: 0 },
    { dishId: 4, ingredientId: 5, quantity: 0 },
    { dishId: 4, ingredientId: 6, quantity: 5 },
    { dishId: 4, ingredientId: 7, quantity: 0 },
    { dishId: 4, ingredientId: 8, quantity: 0 },
    { dishId: 4, ingredientId: 9, quantity: 0 },
    { dishId: 4, ingredientId: 10, quantity: 0 },
    { dishId: 4, ingredientId: 11, quantity: 0 },
    { dishId: 4, ingredientId: 12, quantity: 10 },
    { dishId: 4, ingredientId: 13, quantity: 0 },
    { dishId: 4, ingredientId: 14, quantity: 0 },
    { dishId: 4, ingredientId: 15, quantity: 0 },
    { dishId: 4, ingredientId: 16, quantity: 0 },
    { dishId: 5, ingredientId: 1, quantity: 0 },
    { dishId: 5, ingredientId: 2, quantity: 0 },
    { dishId: 5, ingredientId: 3, quantity: 0 },
    { dishId: 5, ingredientId: 4, quantity: 18 },
    { dishId: 5, ingredientId: 5, quantity: 0 },
    { dishId: 5, ingredientId: 6, quantity: 0 },
    { dishId: 5, ingredientId: 7, quantity: 0 },
    { dishId: 5, ingredientId: 8, quantity: 10 },
    { dishId: 5, ingredientId: 9, quantity: 0 },
    { dishId: 5, ingredientId: 10, quantity: 0 },
    { dishId: 5, ingredientId: 11, quantity: 0 },
    { dishId: 5, ingredientId: 12, quantity: 15 },
    { dishId: 5, ingredientId: 13, quantity: 12 },
    { dishId: 5, ingredientId: 14, quantity: 0 },
    { dishId: 5, ingredientId: 15, quantity: 0 },
    { dishId: 5, ingredientId: 16, quantity: 0 },
    { dishId: 6, ingredientId: 1, quantity: 14 },
    { dishId: 6, ingredientId: 2, quantity: 0 },
    { dishId: 6, ingredientId: 3, quantity: 0 },
    { dishId: 6, ingredientId: 4, quantity: 0 },
    { dishId: 6, ingredientId: 5, quantity: 0 },
    { dishId: 6, ingredientId: 6, quantity: 8 },
    { dishId: 6, ingredientId: 7, quantity: 0 },
    { dishId: 6, ingredientId: 8, quantity: 0 },
    { dishId: 6, ingredientId: 9, quantity: 0 },
    { dishId: 6, ingredientId: 10, quantity: 0 },
    { dishId: 6, ingredientId: 11, quantity: 10 },
    { dishId: 6, ingredientId: 12, quantity: 0 },
    { dishId: 6, ingredientId: 13, quantity: 0 },
    { dishId: 6, ingredientId: 14, quantity: 0 },
    { dishId: 6, ingredientId: 15, quantity: 0 },
    { dishId: 6, ingredientId: 16, quantity: 0 },
    { dishId: 7, ingredientId: 1, quantity: 0 },
    { dishId: 7, ingredientId: 2, quantity: 14 },
    { dishId: 7, ingredientId: 3, quantity: 0 },
    { dishId: 7, ingredientId: 4, quantity: 9 },
    { dishId: 7, ingredientId: 5, quantity: 0 },
    { dishId: 7, ingredientId: 6, quantity: 0 },
    { dishId: 7, ingredientId: 7, quantity: 0 },
    { dishId: 7, ingredientId: 8, quantity: 0 },
    { dishId: 7, ingredientId: 9, quantity: 0 },
    { dishId: 7, ingredientId: 10, quantity: 0 },
    { dishId: 7, ingredientId: 11, quantity: 0 },
    { dishId: 7, ingredientId: 12, quantity: 0 },
    { dishId: 7, ingredientId: 13, quantity: 0 },
    { dishId: 7, ingredientId: 14, quantity: 0 },
    { dishId: 7, ingredientId: 15, quantity: 0 },
    { dishId: 7, ingredientId: 16, quantity: 0 },
    { dishId: 8, ingredientId: 1, quantity: 0 },
    { dishId: 8, ingredientId: 2, quantity: 0 },
    { dishId: 8, ingredientId: 3, quantity: 8 },
    { dishId: 8, ingredientId: 4, quantity: 4 },
    { dishId: 8, ingredientId: 5, quantity: 11 },
    { dishId: 8, ingredientId: 6, quantity: 0 },
    { dishId: 8, ingredientId: 7, quantity: 0 },
    { dishId: 8, ingredientId: 8, quantity: 0 },
    { dishId: 8, ingredientId: 9, quantity: 12 },
    { dishId: 8, ingredientId: 10, quantity: 0 },
    { dishId: 8, ingredientId: 11, quantity: 0 },
    { dishId: 8, ingredientId: 12, quantity: 0 },
    { dishId: 8, ingredientId: 13, quantity: 0 },
    { dishId: 8, ingredientId: 14, quantity: 0 },
    { dishId: 8, ingredientId: 15, quantity: 0 },
    { dishId: 8, ingredientId: 16, quantity: 0 },
    { dishId: 9, ingredientId: 1, quantity: 0 },
    { dishId: 9, ingredientId: 2, quantity: 0 },
    { dishId: 9, ingredientId: 3, quantity: 0 },
    { dishId: 9, ingredientId: 4, quantity: 0 },
    { dishId: 9, ingredientId: 5, quantity: 0 },
    { dishId: 9, ingredientId: 6, quantity: 0 },
    { dishId: 9, ingredientId: 7, quantity: 8 },
    { dishId: 9, ingredientId: 8, quantity: 8 },
    { dishId: 9, ingredientId: 9, quantity: 0 },
    { dishId: 9, ingredientId: 10, quantity: 0 },
    { dishId: 9, ingredientId: 11, quantity: 0 },
    { dishId: 9, ingredientId: 12, quantity: 0 },
    { dishId: 9, ingredientId: 13, quantity: 0 },
    { dishId: 9, ingredientId: 14, quantity: 0 },
    { dishId: 9, ingredientId: 15, quantity: 0 },
    { dishId: 9, ingredientId: 16, quantity: 0 },
    { dishId: 10, ingredientId: 1, quantity: 0 },
    { dishId: 10, ingredientId: 2, quantity: 4 },
    { dishId: 10, ingredientId: 3, quantity: 0 },
    { dishId: 10, ingredientId: 4, quantity: 8 },
    { dishId: 10, ingredientId: 5, quantity: 0 },
    { dishId: 10, ingredientId: 6, quantity: 0 },
    { dishId: 10, ingredientId: 7, quantity: 0 },
    { dishId: 10, ingredientId: 8, quantity: 10 },
    { dishId: 10, ingredientId: 9, quantity: 0 },
    { dishId: 10, ingredientId: 10, quantity: 0 },
    { dishId: 10, ingredientId: 11, quantity: 0 },
    { dishId: 10, ingredientId: 12, quantity: 0 },
    { dishId: 10, ingredientId: 13, quantity: 0 },
    { dishId: 10, ingredientId: 14, quantity: 0 },
    { dishId: 10, ingredientId: 15, quantity: 0 },
    { dishId: 10, ingredientId: 16, quantity: 0 },
    { dishId: 11, ingredientId: 1, quantity: 0 },
    { dishId: 11, ingredientId: 2, quantity: 0 },
    { dishId: 11, ingredientId: 3, quantity: 0 },
    { dishId: 11, ingredientId: 4, quantity: 0 },
    { dishId: 11, ingredientId: 5, quantity: 0 },
    { dishId: 11, ingredientId: 6, quantity: 0 },
    { dishId: 11, ingredientId: 7, quantity: 0 },
    { dishId: 11, ingredientId: 8, quantity: 7 },
    { dishId: 11, ingredientId: 9, quantity: 0 },
    { dishId: 11, ingredientId: 10, quantity: 0 },
    { dishId: 11, ingredientId: 11, quantity: 0 },
    { dishId: 11, ingredientId: 12, quantity: 0 },
    { dishId: 11, ingredientId: 13, quantity: 0 },
    { dishId: 11, ingredientId: 14, quantity: 0 },
    { dishId: 11, ingredientId: 15, quantity: 0 },
    { dishId: 11, ingredientId: 16, quantity: 0 },
    { dishId: 12, ingredientId: 1, quantity: 0 },
    { dishId: 12, ingredientId: 2, quantity: 0 },
    { dishId: 12, ingredientId: 3, quantity: 0 },
    { dishId: 12, ingredientId: 4, quantity: 0 },
    { dishId: 12, ingredientId: 5, quantity: 0 },
    { dishId: 12, ingredientId: 6, quantity: 0 },
    { dishId: 12, ingredientId: 7, quantity: 7 },
    { dishId: 12, ingredientId: 8, quantity: 0 },
    { dishId: 12, ingredientId: 9, quantity: 0 },
    { dishId: 12, ingredientId: 10, quantity: 0 },
    { dishId: 12, ingredientId: 11, quantity: 0 },
    { dishId: 12, ingredientId: 12, quantity: 0 },
    { dishId: 12, ingredientId: 13, quantity: 0 },
    { dishId: 12, ingredientId: 14, quantity: 0 },
    { dishId: 12, ingredientId: 15, quantity: 0 },
    { dishId: 12, ingredientId: 16, quantity: 0 },
    { dishId: 13, ingredientId: 1, quantity: 0 },
    { dishId: 13, ingredientId: 2, quantity: 0 },
    { dishId: 13, ingredientId: 3, quantity: 0 },
    { dishId: 13, ingredientId: 4, quantity: 0 },
    { dishId: 13, ingredientId: 5, quantity: 0 },
    { dishId: 13, ingredientId: 6, quantity: 0 },
    { dishId: 13, ingredientId: 7, quantity: 0 },
    { dishId: 13, ingredientId: 8, quantity: 0 },
    { dishId: 13, ingredientId: 9, quantity: 7 },
    { dishId: 13, ingredientId: 10, quantity: 0 },
    { dishId: 13, ingredientId: 11, quantity: 0 },
    { dishId: 13, ingredientId: 12, quantity: 0 },
    { dishId: 13, ingredientId: 13, quantity: 0 },
    { dishId: 13, ingredientId: 14, quantity: 0 },
    { dishId: 13, ingredientId: 15, quantity: 0 },
    { dishId: 13, ingredientId: 16, quantity: 0 },
    { dishId: 14, ingredientId: 1, quantity: 9 },
    { dishId: 14, ingredientId: 2, quantity: 5 },
    { dishId: 14, ingredientId: 3, quantity: 0 },
    { dishId: 14, ingredientId: 4, quantity: 0 },
    { dishId: 14, ingredientId: 5, quantity: 0 },
    { dishId: 14, ingredientId: 6, quantity: 0 },
    { dishId: 14, ingredientId: 7, quantity: 9 },
    { dishId: 14, ingredientId: 8, quantity: 0 },
    { dishId: 14, ingredientId: 9, quantity: 0 },
    { dishId: 14, ingredientId: 10, quantity: 0 },
    { dishId: 14, ingredientId: 11, quantity: 0 },
    { dishId: 14, ingredientId: 12, quantity: 0 },
    { dishId: 14, ingredientId: 13, quantity: 0 },
    { dishId: 14, ingredientId: 14, quantity: 0 },
    { dishId: 14, ingredientId: 15, quantity: 15 },
    { dishId: 14, ingredientId: 16, quantity: 0 },
    { dishId: 15, ingredientId: 1, quantity: 0 },
    { dishId: 15, ingredientId: 2, quantity: 0 },
    { dishId: 15, ingredientId: 3, quantity: 0 },
    { dishId: 15, ingredientId: 4, quantity: 0 },
    { dishId: 15, ingredientId: 5, quantity: 0 },
    { dishId: 15, ingredientId: 6, quantity: 0 },
    { dishId: 15, ingredientId: 7, quantity: 10 },
    { dishId: 15, ingredientId: 8, quantity: 0 },
    { dishId: 15, ingredientId: 9, quantity: 0 },
    { dishId: 15, ingredientId: 10, quantity: 5 },
    { dishId: 15, ingredientId: 11, quantity: 0 },
    { dishId: 15, ingredientId: 12, quantity: 0 },
    { dishId: 15, ingredientId: 13, quantity: 0 },
    { dishId: 15, ingredientId: 14, quantity: 0 },
    { dishId: 15, ingredientId: 15, quantity: 0 },
    { dishId: 15, ingredientId: 16, quantity: 0 },
    { dishId: 16, ingredientId: 1, quantity: 0 },
    { dishId: 16, ingredientId: 2, quantity: 0 },
    { dishId: 16, ingredientId: 3, quantity: 10 },
    { dishId: 16, ingredientId: 4, quantity: 0 },
    { dishId: 16, ingredientId: 5, quantity: 0 },
    { dishId: 16, ingredientId: 6, quantity: 0 },
    { dishId: 16, ingredientId: 7, quantity: 0 },
    { dishId: 16, ingredientId: 8, quantity: 0 },
    { dishId: 16, ingredientId: 9, quantity: 0 },
    { dishId: 16, ingredientId: 10, quantity: 0 },
    { dishId: 16, ingredientId: 11, quantity: 0 },
    { dishId: 16, ingredientId: 12, quantity: 6 },
    { dishId: 16, ingredientId: 13, quantity: 0 },
    { dishId: 16, ingredientId: 14, quantity: 0 },
    { dishId: 16, ingredientId: 15, quantity: 0 },
    { dishId: 16, ingredientId: 16, quantity: 0 },
    { dishId: 17, ingredientId: 1, quantity: 0 },
    { dishId: 17, ingredientId: 2, quantity: 0 },
    { dishId: 17, ingredientId: 3, quantity: 4 },
    { dishId: 17, ingredientId: 4, quantity: 0 },
    { dishId: 17, ingredientId: 5, quantity: 0 },
    { dishId: 17, ingredientId: 6, quantity: 4 },
    { dishId: 17, ingredientId: 7, quantity: 6 },
    { dishId: 17, ingredientId: 8, quantity: 0 },
    { dishId: 17, ingredientId: 9, quantity: 0 },
    { dishId: 17, ingredientId: 10, quantity: 0 },
    { dishId: 17, ingredientId: 11, quantity: 0 },
    { dishId: 17, ingredientId: 12, quantity: 0 },
    { dishId: 17, ingredientId: 13, quantity: 0 },
    { dishId: 17, ingredientId: 14, quantity: 0 },
    { dishId: 17, ingredientId: 15, quantity: 12 },
    { dishId: 17, ingredientId: 16, quantity: 0 },
    { dishId: 18, ingredientId: 1, quantity: 0 },
    { dishId: 18, ingredientId: 2, quantity: 0 },
    { dishId: 18, ingredientId: 3, quantity: 0 },
    { dishId: 18, ingredientId: 4, quantity: 8 },
    { dishId: 18, ingredientId: 5, quantity: 0 },
    { dishId: 18, ingredientId: 6, quantity: 0 },
    { dishId: 18, ingredientId: 7, quantity: 0 },
    { dishId: 18, ingredientId: 8, quantity: 8 },
    { dishId: 18, ingredientId: 9, quantity: 0 },
    { dishId: 18, ingredientId: 10, quantity: 0 },
    { dishId: 18, ingredientId: 11, quantity: 0 },
    { dishId: 18, ingredientId: 12, quantity: 0 },
    { dishId: 18, ingredientId: 13, quantity: 0 },
    { dishId: 18, ingredientId: 14, quantity: 0 },
    { dishId: 18, ingredientId: 15, quantity: 0 },
    { dishId: 18, ingredientId: 16, quantity: 14 },
    { dishId: 19, ingredientId: 1, quantity: 0 },
    { dishId: 19, ingredientId: 2, quantity: 0 },
    { dishId: 19, ingredientId: 3, quantity: 0 },
    { dishId: 19, ingredientId: 4, quantity: 0 },
    { dishId: 19, ingredientId: 5, quantity: 0 },
    { dishId: 19, ingredientId: 6, quantity: 27 },
    { dishId: 19, ingredientId: 7, quantity: 24 },
    { dishId: 19, ingredientId: 8, quantity: 0 },
    { dishId: 19, ingredientId: 9, quantity: 0 },
    { dishId: 19, ingredientId: 10, quantity: 0 },
    { dishId: 19, ingredientId: 11, quantity: 12 },
    { dishId: 19, ingredientId: 12, quantity: 0 },
    { dishId: 19, ingredientId: 13, quantity: 0 },
    { dishId: 19, ingredientId: 14, quantity: 0 },
    { dishId: 19, ingredientId: 15, quantity: 0 },
    { dishId: 19, ingredientId: 16, quantity: 14 },
    { dishId: 20, ingredientId: 1, quantity: 0 },
    { dishId: 20, ingredientId: 2, quantity: 0 },
    { dishId: 20, ingredientId: 3, quantity: 0 },
    { dishId: 20, ingredientId: 4, quantity: 0 },
    { dishId: 20, ingredientId: 5, quantity: 0 },
    { dishId: 20, ingredientId: 6, quantity: 0 },
    { dishId: 20, ingredientId: 7, quantity: 0 },
    { dishId: 20, ingredientId: 8, quantity: 0 },
    { dishId: 20, ingredientId: 9, quantity: 0 },
    { dishId: 20, ingredientId: 10, quantity: 0 },
    { dishId: 20, ingredientId: 11, quantity: 0 },
    { dishId: 20, ingredientId: 12, quantity: 0 },
    { dishId: 20, ingredientId: 13, quantity: 0 },
    { dishId: 20, ingredientId: 14, quantity: 0 },
    { dishId: 20, ingredientId: 15, quantity: 0 },
    { dishId: 20, ingredientId: 16, quantity: 0 },
    { dishId: 21, ingredientId: 1, quantity: 0 },
    { dishId: 21, ingredientId: 2, quantity: 0 },
    { dishId: 21, ingredientId: 3, quantity: 0 },
    { dishId: 21, ingredientId: 4, quantity: 0 },
    { dishId: 21, ingredientId: 5, quantity: 0 },
    { dishId: 21, ingredientId: 6, quantity: 10 },
    { dishId: 21, ingredientId: 7, quantity: 0 },
    { dishId: 21, ingredientId: 8, quantity: 0 },
    { dishId: 21, ingredientId: 9, quantity: 0 },
    { dishId: 21, ingredientId: 10, quantity: 15 },
    { dishId: 21, ingredientId: 11, quantity: 0 },
    { dishId: 21, ingredientId: 12, quantity: 0 },
    { dishId: 21, ingredientId: 13, quantity: 0 },
    { dishId: 21, ingredientId: 14, quantity: 10 },
    { dishId: 21, ingredientId: 15, quantity: 0 },
    { dishId: 21, ingredientId: 16, quantity: 0 },
    { dishId: 22, ingredientId: 1, quantity: 0 },
    { dishId: 22, ingredientId: 2, quantity: 17 },
    { dishId: 22, ingredientId: 3, quantity: 0 },
    { dishId: 22, ingredientId: 4, quantity: 0 },
    { dishId: 22, ingredientId: 5, quantity: 0 },
    { dishId: 22, ingredientId: 6, quantity: 0 },
    { dishId: 22, ingredientId: 7, quantity: 0 },
    { dishId: 22, ingredientId: 8, quantity: 0 },
    { dishId: 22, ingredientId: 9, quantity: 0 },
    { dishId: 22, ingredientId: 10, quantity: 8 },
    { dishId: 22, ingredientId: 11, quantity: 0 },
    { dishId: 22, ingredientId: 12, quantity: 8 },
    { dishId: 22, ingredientId: 13, quantity: 0 },
    { dishId: 22, ingredientId: 14, quantity: 0 },
    { dishId: 22, ingredientId: 15, quantity: 0 },
    { dishId: 22, ingredientId: 16, quantity: 0 },
    { dishId: 23, ingredientId: 1, quantity: 0 },
    { dishId: 23, ingredientId: 2, quantity: 0 },
    { dishId: 23, ingredientId: 3, quantity: 0 },
    { dishId: 23, ingredientId: 4, quantity: 0 },
    { dishId: 23, ingredientId: 5, quantity: 0 },
    { dishId: 23, ingredientId: 6, quantity: 0 },
    { dishId: 23, ingredientId: 7, quantity: 6 },
    { dishId: 23, ingredientId: 8, quantity: 10 },
    { dishId: 23, ingredientId: 9, quantity: 0 },
    { dishId: 23, ingredientId: 10, quantity: 0 },
    { dishId: 23, ingredientId: 11, quantity: 0 },
    { dishId: 23, ingredientId: 12, quantity: 0 },
    { dishId: 23, ingredientId: 13, quantity: 0 },
    { dishId: 23, ingredientId: 14, quantity: 0 },
    { dishId: 23, ingredientId: 15, quantity: 0 },
    { dishId: 23, ingredientId: 16, quantity: 0 },
    { dishId: 24, ingredientId: 1, quantity: 0 },
    { dishId: 24, ingredientId: 2, quantity: 0 },
    { dishId: 24, ingredientId: 3, quantity: 9 },
    { dishId: 24, ingredientId: 4, quantity: 14 },
    { dishId: 24, ingredientId: 5, quantity: 6 },
    { dishId: 24, ingredientId: 6, quantity: 0 },
    { dishId: 24, ingredientId: 7, quantity: 7 },
    { dishId: 24, ingredientId: 8, quantity: 0 },
    { dishId: 24, ingredientId: 9, quantity: 0 },
    { dishId: 24, ingredientId: 10, quantity: 0 },
    { dishId: 24, ingredientId: 11, quantity: 0 },
    { dishId: 24, ingredientId: 12, quantity: 0 },
    { dishId: 24, ingredientId: 13, quantity: 0 },
    { dishId: 24, ingredientId: 14, quantity: 0 },
    { dishId: 24, ingredientId: 15, quantity: 0 },
    { dishId: 24, ingredientId: 16, quantity: 0 },
    { dishId: 25, ingredientId: 1, quantity: 0 },
    { dishId: 25, ingredientId: 2, quantity: 0 },
    { dishId: 25, ingredientId: 3, quantity: 0 },
    { dishId: 25, ingredientId: 4, quantity: 0 },
    { dishId: 25, ingredientId: 5, quantity: 0 },
    { dishId: 25, ingredientId: 6, quantity: 0 },
    { dishId: 25, ingredientId: 7, quantity: 0 },
    { dishId: 25, ingredientId: 8, quantity: 0 },
    { dishId: 25, ingredientId: 9, quantity: 0 },
    { dishId: 25, ingredientId: 10, quantity: 0 },
    { dishId: 25, ingredientId: 11, quantity: 0 },
    { dishId: 25, ingredientId: 12, quantity: 6 },
    { dishId: 25, ingredientId: 13, quantity: 0 },
    { dishId: 25, ingredientId: 14, quantity: 0 },
    { dishId: 25, ingredientId: 15, quantity: 10 },
    { dishId: 25, ingredientId: 16, quantity: 0 },
    { dishId: 26, ingredientId: 1, quantity: 0 },
    { dishId: 26, ingredientId: 2, quantity: 0 },
    { dishId: 26, ingredientId: 3, quantity: 5 },
    { dishId: 26, ingredientId: 4, quantity: 3 },
    { dishId: 26, ingredientId: 5, quantity: 0 },
    { dishId: 26, ingredientId: 6, quantity: 0 },
    { dishId: 26, ingredientId: 7, quantity: 9 },
    { dishId: 26, ingredientId: 8, quantity: 0 },
    { dishId: 26, ingredientId: 9, quantity: 0 },
    { dishId: 26, ingredientId: 10, quantity: 0 },
    { dishId: 26, ingredientId: 11, quantity: 6 },
    { dishId: 26, ingredientId: 12, quantity: 0 },
    { dishId: 26, ingredientId: 13, quantity: 0 },
    { dishId: 26, ingredientId: 14, quantity: 0 },
    { dishId: 26, ingredientId: 15, quantity: 0 },
    { dishId: 26, ingredientId: 16, quantity: 0 },
    { dishId: 27, ingredientId: 1, quantity: 0 },
    { dishId: 27, ingredientId: 2, quantity: 0 },
    { dishId: 27, ingredientId: 3, quantity: 0 },
    { dishId: 27, ingredientId: 4, quantity: 0 },
    { dishId: 27, ingredientId: 5, quantity: 0 },
    { dishId: 27, ingredientId: 6, quantity: 0 },
    { dishId: 27, ingredientId: 7, quantity: 8 },
    { dishId: 27, ingredientId: 8, quantity: 0 },
    { dishId: 27, ingredientId: 9, quantity: 0 },
    { dishId: 27, ingredientId: 10, quantity: 0 },
    { dishId: 27, ingredientId: 11, quantity: 0 },
    { dishId: 27, ingredientId: 12, quantity: 0 },
    { dishId: 27, ingredientId: 13, quantity: 0 },
    { dishId: 27, ingredientId: 14, quantity: 0 },
    { dishId: 27, ingredientId: 15, quantity: 0 },
    { dishId: 27, ingredientId: 16, quantity: 0 },
    { dishId: 28, ingredientId: 1, quantity: 0 },
    { dishId: 28, ingredientId: 2, quantity: 0 },
    { dishId: 28, ingredientId: 3, quantity: 0 },
    { dishId: 28, ingredientId: 4, quantity: 0 },
    { dishId: 28, ingredientId: 5, quantity: 0 },
    { dishId: 28, ingredientId: 6, quantity: 0 },
    { dishId: 28, ingredientId: 7, quantity: 0 },
    { dishId: 28, ingredientId: 8, quantity: 0 },
    { dishId: 28, ingredientId: 9, quantity: 0 },
    { dishId: 28, ingredientId: 10, quantity: 0 },
    { dishId: 28, ingredientId: 11, quantity: 0 },
    { dishId: 28, ingredientId: 12, quantity: 8 },
    { dishId: 28, ingredientId: 13, quantity: 0 },
    { dishId: 28, ingredientId: 14, quantity: 0 },
    { dishId: 28, ingredientId: 15, quantity: 0 },
    { dishId: 28, ingredientId: 16, quantity: 0 },
    { dishId: 29, ingredientId: 1, quantity: 0 },
    { dishId: 29, ingredientId: 2, quantity: 0 },
    { dishId: 29, ingredientId: 3, quantity: 0 },
    { dishId: 29, ingredientId: 4, quantity: 0 },
    { dishId: 29, ingredientId: 5, quantity: 0 },
    { dishId: 29, ingredientId: 6, quantity: 0 },
    { dishId: 29, ingredientId: 7, quantity: 0 },
    { dishId: 29, ingredientId: 8, quantity: 12 },
    { dishId: 29, ingredientId: 9, quantity: 0 },
    { dishId: 29, ingredientId: 10, quantity: 5 },
    { dishId: 29, ingredientId: 11, quantity: 0 },
    { dishId: 29, ingredientId: 12, quantity: 6 },
    { dishId: 29, ingredientId: 13, quantity: 0 },
    { dishId: 29, ingredientId: 14, quantity: 0 },
    { dishId: 29, ingredientId: 15, quantity: 0 },
    { dishId: 29, ingredientId: 16, quantity: 0 },
    { dishId: 30, ingredientId: 1, quantity: 0 },
    { dishId: 30, ingredientId: 2, quantity: 0 },
    { dishId: 30, ingredientId: 3, quantity: 0 },
    { dishId: 30, ingredientId: 4, quantity: 0 },
    { dishId: 30, ingredientId: 5, quantity: 0 },
    { dishId: 30, ingredientId: 6, quantity: 0 },
    { dishId: 30, ingredientId: 7, quantity: 9 },
    { dishId: 30, ingredientId: 8, quantity: 0 },
    { dishId: 30, ingredientId: 9, quantity: 0 },
    { dishId: 30, ingredientId: 10, quantity: 0 },
    { dishId: 30, ingredientId: 11, quantity: 0 },
    { dishId: 30, ingredientId: 12, quantity: 0 },
    { dishId: 30, ingredientId: 13, quantity: 14 },
    { dishId: 30, ingredientId: 14, quantity: 0 },
    { dishId: 30, ingredientId: 15, quantity: 0 },
    { dishId: 30, ingredientId: 16, quantity: 0 },
    { dishId: 31, ingredientId: 1, quantity: 0 },
    { dishId: 31, ingredientId: 2, quantity: 0 },
    { dishId: 31, ingredientId: 3, quantity: 0 },
    { dishId: 31, ingredientId: 4, quantity: 0 },
    { dishId: 31, ingredientId: 5, quantity: 0 },
    { dishId: 31, ingredientId: 6, quantity: 17 },
    { dishId: 31, ingredientId: 7, quantity: 0 },
    { dishId: 31, ingredientId: 8, quantity: 0 },
    { dishId: 31, ingredientId: 9, quantity: 0 },
    { dishId: 31, ingredientId: 10, quantity: 0 },
    { dishId: 31, ingredientId: 11, quantity: 10 },
    { dishId: 31, ingredientId: 12, quantity: 8 },
    { dishId: 31, ingredientId: 13, quantity: 0 },
    { dishId: 31, ingredientId: 14, quantity: 0 },
    { dishId: 31, ingredientId: 15, quantity: 0 },
    { dishId: 31, ingredientId: 16, quantity: 0 },
    { dishId: 32, ingredientId: 1, quantity: 0 },
    { dishId: 32, ingredientId: 2, quantity: 0 },
    { dishId: 32, ingredientId: 3, quantity: 0 },
    { dishId: 32, ingredientId: 4, quantity: 0 },
    { dishId: 32, ingredientId: 5, quantity: 8 },
    { dishId: 32, ingredientId: 6, quantity: 0 },
    { dishId: 32, ingredientId: 7, quantity: 0 },
    { dishId: 32, ingredientId: 8, quantity: 0 },
    { dishId: 32, ingredientId: 9, quantity: 0 },
    { dishId: 32, ingredientId: 10, quantity: 0 },
    { dishId: 32, ingredientId: 11, quantity: 0 },
    { dishId: 32, ingredientId: 12, quantity: 0 },
    { dishId: 32, ingredientId: 13, quantity: 0 },
    { dishId: 32, ingredientId: 14, quantity: 0 },
    { dishId: 32, ingredientId: 15, quantity: 0 },
    { dishId: 32, ingredientId: 16, quantity: 0 },
    { dishId: 33, ingredientId: 1, quantity: 10 },
    { dishId: 33, ingredientId: 2, quantity: 0 },
    { dishId: 33, ingredientId: 3, quantity: 0 },
    { dishId: 33, ingredientId: 4, quantity: 0 },
    { dishId: 33, ingredientId: 5, quantity: 0 },
    { dishId: 33, ingredientId: 6, quantity: 0 },
    { dishId: 33, ingredientId: 7, quantity: 0 },
    { dishId: 33, ingredientId: 8, quantity: 0 },
    { dishId: 33, ingredientId: 9, quantity: 0 },
    { dishId: 33, ingredientId: 10, quantity: 0 },
    { dishId: 33, ingredientId: 11, quantity: 5 },
    { dishId: 33, ingredientId: 12, quantity: 0 },
    { dishId: 33, ingredientId: 13, quantity: 0 },
    { dishId: 33, ingredientId: 14, quantity: 0 },
    { dishId: 33, ingredientId: 15, quantity: 0 },
    { dishId: 33, ingredientId: 16, quantity: 0 },
    { dishId: 34, ingredientId: 1, quantity: 0 },
    { dishId: 34, ingredientId: 2, quantity: 0 },
    { dishId: 34, ingredientId: 3, quantity: 0 },
    { dishId: 34, ingredientId: 4, quantity: 0 },
    { dishId: 34, ingredientId: 5, quantity: 15 },
    { dishId: 34, ingredientId: 6, quantity: 0 },
    { dishId: 34, ingredientId: 7, quantity: 0 },
    { dishId: 34, ingredientId: 8, quantity: 5 },
    { dishId: 34, ingredientId: 9, quantity: 0 },
    { dishId: 34, ingredientId: 10, quantity: 3 },
    { dishId: 34, ingredientId: 11, quantity: 0 },
    { dishId: 34, ingredientId: 12, quantity: 0 },
    { dishId: 34, ingredientId: 13, quantity: 0 },
    { dishId: 34, ingredientId: 14, quantity: 0 },
    { dishId: 34, ingredientId: 15, quantity: 0 },
    { dishId: 34, ingredientId: 16, quantity: 0 },
    { dishId: 35, ingredientId: 1, quantity: 15 },
    { dishId: 35, ingredientId: 2, quantity: 12 },
    { dishId: 35, ingredientId: 3, quantity: 0 },
    { dishId: 35, ingredientId: 4, quantity: 0 },
    { dishId: 35, ingredientId: 5, quantity: 0 },
    { dishId: 35, ingredientId: 6, quantity: 0 },
    { dishId: 35, ingredientId: 7, quantity: 0 },
    { dishId: 35, ingredientId: 8, quantity: 0 },
    { dishId: 35, ingredientId: 9, quantity: 0 },
    { dishId: 35, ingredientId: 10, quantity: 0 },
    { dishId: 35, ingredientId: 11, quantity: 11 },
    { dishId: 35, ingredientId: 12, quantity: 0 },
    { dishId: 35, ingredientId: 13, quantity: 0 },
    { dishId: 35, ingredientId: 14, quantity: 0 },
    { dishId: 35, ingredientId: 15, quantity: 15 },
    { dishId: 35, ingredientId: 16, quantity: 0 },
    { dishId: 36, ingredientId: 1, quantity: 0 },
    { dishId: 36, ingredientId: 2, quantity: 0 },
    { dishId: 36, ingredientId: 3, quantity: 0 },
    { dishId: 36, ingredientId: 4, quantity: 0 },
    { dishId: 36, ingredientId: 5, quantity: 0 },
    { dishId: 36, ingredientId: 6, quantity: 6 },
    { dishId: 36, ingredientId: 7, quantity: 0 },
    { dishId: 36, ingredientId: 8, quantity: 0 },
    { dishId: 36, ingredientId: 9, quantity: 0 },
    { dishId: 36, ingredientId: 10, quantity: 0 },
    { dishId: 36, ingredientId: 11, quantity: 0 },
    { dishId: 36, ingredientId: 12, quantity: 0 },
    { dishId: 36, ingredientId: 13, quantity: 0 },
    { dishId: 36, ingredientId: 14, quantity: 0 },
    { dishId: 36, ingredientId: 15, quantity: 10 },
    { dishId: 36, ingredientId: 16, quantity: 0 },
    { dishId: 37, ingredientId: 1, quantity: 0 },
    { dishId: 37, ingredientId: 2, quantity: 0 },
    { dishId: 37, ingredientId: 3, quantity: 0 },
    { dishId: 37, ingredientId: 4, quantity: 9 },
    { dishId: 37, ingredientId: 5, quantity: 0 },
    { dishId: 37, ingredientId: 6, quantity: 0 },
    { dishId: 37, ingredientId: 7, quantity: 0 },
    { dishId: 37, ingredientId: 8, quantity: 0 },
    { dishId: 37, ingredientId: 9, quantity: 0 },
    { dishId: 37, ingredientId: 10, quantity: 22 },
    { dishId: 37, ingredientId: 11, quantity: 0 },
    { dishId: 37, ingredientId: 12, quantity: 14 },
    { dishId: 37, ingredientId: 13, quantity: 0 },
    { dishId: 37, ingredientId: 14, quantity: 0 },
    { dishId: 37, ingredientId: 15, quantity: 0 },
    { dishId: 37, ingredientId: 16, quantity: 17 },
    { dishId: 38, ingredientId: 1, quantity: 0 },
    { dishId: 38, ingredientId: 2, quantity: 0 },
    { dishId: 38, ingredientId: 3, quantity: 0 },
    { dishId: 38, ingredientId: 4, quantity: 0 },
    { dishId: 38, ingredientId: 5, quantity: 21 },
    { dishId: 38, ingredientId: 6, quantity: 0 },
    { dishId: 38, ingredientId: 7, quantity: 0 },
    { dishId: 38, ingredientId: 8, quantity: 0 },
    { dishId: 38, ingredientId: 9, quantity: 16 },
    { dishId: 38, ingredientId: 10, quantity: 0 },
    { dishId: 38, ingredientId: 11, quantity: 0 },
    { dishId: 38, ingredientId: 12, quantity: 0 },
    { dishId: 38, ingredientId: 13, quantity: 0 },
    { dishId: 38, ingredientId: 14, quantity: 0 },
    { dishId: 38, ingredientId: 15, quantity: 0 },
    { dishId: 38, ingredientId: 16, quantity: 12 },
    { dishId: 39, ingredientId: 1, quantity: 0 },
    { dishId: 39, ingredientId: 2, quantity: 0 },
    { dishId: 39, ingredientId: 3, quantity: 0 },
    { dishId: 39, ingredientId: 4, quantity: 0 },
    { dishId: 39, ingredientId: 5, quantity: 0 },
    { dishId: 39, ingredientId: 6, quantity: 0 },
    { dishId: 39, ingredientId: 7, quantity: 0 },
    { dishId: 39, ingredientId: 8, quantity: 0 },
    { dishId: 39, ingredientId: 9, quantity: 0 },
    { dishId: 39, ingredientId: 10, quantity: 8 },
    { dishId: 39, ingredientId: 11, quantity: 0 },
    { dishId: 39, ingredientId: 12, quantity: 0 },
    { dishId: 39, ingredientId: 13, quantity: 0 },
    { dishId: 39, ingredientId: 14, quantity: 0 },
    { dishId: 39, ingredientId: 15, quantity: 0 },
    { dishId: 39, ingredientId: 16, quantity: 9 },
    { dishId: 40, ingredientId: 1, quantity: 0 },
    { dishId: 40, ingredientId: 2, quantity: 0 },
    { dishId: 40, ingredientId: 3, quantity: 0 },
    { dishId: 40, ingredientId: 4, quantity: 0 },
    { dishId: 40, ingredientId: 5, quantity: 0 },
    { dishId: 40, ingredientId: 6, quantity: 0 },
    { dishId: 40, ingredientId: 7, quantity: 0 },
    { dishId: 40, ingredientId: 8, quantity: 0 },
    { dishId: 40, ingredientId: 9, quantity: 0 },
    { dishId: 40, ingredientId: 10, quantity: 0 },
    { dishId: 40, ingredientId: 11, quantity: 0 },
    { dishId: 40, ingredientId: 12, quantity: 0 },
    { dishId: 40, ingredientId: 13, quantity: 0 },
    { dishId: 40, ingredientId: 14, quantity: 0 },
    { dishId: 40, ingredientId: 15, quantity: 0 },
    { dishId: 40, ingredientId: 16, quantity: 0 },
    { dishId: 41, ingredientId: 1, quantity: 0 },
    { dishId: 41, ingredientId: 2, quantity: 0 },
    { dishId: 41, ingredientId: 3, quantity: 0 },
    { dishId: 41, ingredientId: 4, quantity: 9 },
    { dishId: 41, ingredientId: 5, quantity: 0 },
    { dishId: 41, ingredientId: 6, quantity: 0 },
    { dishId: 41, ingredientId: 7, quantity: 0 },
    { dishId: 41, ingredientId: 8, quantity: 5 },
    { dishId: 41, ingredientId: 9, quantity: 0 },
    { dishId: 41, ingredientId: 10, quantity: 0 },
    { dishId: 41, ingredientId: 11, quantity: 0 },
    { dishId: 41, ingredientId: 12, quantity: 0 },
    { dishId: 41, ingredientId: 13, quantity: 0 },
    { dishId: 41, ingredientId: 14, quantity: 0 },
    { dishId: 41, ingredientId: 15, quantity: 0 },
    { dishId: 41, ingredientId: 16, quantity: 0 },
    { dishId: 42, ingredientId: 1, quantity: 0 },
    { dishId: 42, ingredientId: 2, quantity: 0 },
    { dishId: 42, ingredientId: 3, quantity: 4 },
    { dishId: 42, ingredientId: 4, quantity: 0 },
    { dishId: 42, ingredientId: 5, quantity: 0 },
    { dishId: 42, ingredientId: 6, quantity: 0 },
    { dishId: 42, ingredientId: 7, quantity: 0 },
    { dishId: 42, ingredientId: 8, quantity: 0 },
    { dishId: 42, ingredientId: 9, quantity: 14 },
    { dishId: 42, ingredientId: 10, quantity: 0 },
    { dishId: 42, ingredientId: 11, quantity: 12 },
    { dishId: 42, ingredientId: 12, quantity: 0 },
    { dishId: 42, ingredientId: 13, quantity: 5 },
    { dishId: 42, ingredientId: 14, quantity: 0 },
    { dishId: 42, ingredientId: 15, quantity: 0 },
    { dishId: 42, ingredientId: 16, quantity: 0 },
    { dishId: 43, ingredientId: 1, quantity: 0 },
    { dishId: 43, ingredientId: 2, quantity: 0 },
    { dishId: 43, ingredientId: 3, quantity: 0 },
    { dishId: 43, ingredientId: 4, quantity: 0 },
    { dishId: 43, ingredientId: 5, quantity: 8 },
    { dishId: 43, ingredientId: 6, quantity: 0 },
    { dishId: 43, ingredientId: 7, quantity: 0 },
    { dishId: 43, ingredientId: 8, quantity: 0 },
    { dishId: 43, ingredientId: 9, quantity: 0 },
    { dishId: 43, ingredientId: 10, quantity: 0 },
    { dishId: 43, ingredientId: 11, quantity: 0 },
    { dishId: 43, ingredientId: 12, quantity: 0 },
    { dishId: 43, ingredientId: 13, quantity: 0 },
    { dishId: 43, ingredientId: 14, quantity: 0 },
    { dishId: 43, ingredientId: 15, quantity: 0 },
    { dishId: 43, ingredientId: 16, quantity: 0 },
    { dishId: 44, ingredientId: 1, quantity: 0 },
    { dishId: 44, ingredientId: 2, quantity: 0 },
    { dishId: 44, ingredientId: 3, quantity: 0 },
    { dishId: 44, ingredientId: 4, quantity: 0 },
    { dishId: 44, ingredientId: 5, quantity: 0 },
    { dishId: 44, ingredientId: 6, quantity: 0 },
    { dishId: 44, ingredientId: 7, quantity: 0 },
    { dishId: 44, ingredientId: 8, quantity: 0 },
    { dishId: 44, ingredientId: 9, quantity: 9 },
    { dishId: 44, ingredientId: 10, quantity: 0 },
    { dishId: 44, ingredientId: 11, quantity: 0 },
    { dishId: 44, ingredientId: 12, quantity: 0 },
    { dishId: 44, ingredientId: 13, quantity: 0 },
    { dishId: 44, ingredientId: 14, quantity: 0 },
    { dishId: 44, ingredientId: 15, quantity: 0 },
    { dishId: 44, ingredientId: 16, quantity: 0 },
    { dishId: 45, ingredientId: 1, quantity: 0 },
    { dishId: 45, ingredientId: 2, quantity: 0 },
    { dishId: 45, ingredientId: 3, quantity: 0 },
    { dishId: 45, ingredientId: 4, quantity: 0 },
    { dishId: 45, ingredientId: 5, quantity: 7 },
    { dishId: 45, ingredientId: 6, quantity: 0 },
    { dishId: 45, ingredientId: 7, quantity: 0 },
    { dishId: 45, ingredientId: 8, quantity: 0 },
    { dishId: 45, ingredientId: 9, quantity: 0 },
    { dishId: 45, ingredientId: 10, quantity: 0 },
    { dishId: 45, ingredientId: 11, quantity: 9 },
    { dishId: 45, ingredientId: 12, quantity: 0 },
    { dishId: 45, ingredientId: 13, quantity: 0 },
    { dishId: 45, ingredientId: 14, quantity: 0 },
    { dishId: 45, ingredientId: 15, quantity: 0 },
    { dishId: 45, ingredientId: 16, quantity: 0 },
    { dishId: 46, ingredientId: 1, quantity: 0 },
    { dishId: 46, ingredientId: 2, quantity: 0 },
    { dishId: 46, ingredientId: 3, quantity: 15 },
    { dishId: 46, ingredientId: 4, quantity: 0 },
    { dishId: 46, ingredientId: 5, quantity: 10 },
    { dishId: 46, ingredientId: 6, quantity: 0 },
    { dishId: 46, ingredientId: 7, quantity: 0 },
    { dishId: 46, ingredientId: 8, quantity: 10 },
    { dishId: 46, ingredientId: 9, quantity: 20 },
    { dishId: 46, ingredientId: 10, quantity: 0 },
    { dishId: 46, ingredientId: 11, quantity: 0 },
    { dishId: 46, ingredientId: 12, quantity: 0 },
    { dishId: 46, ingredientId: 13, quantity: 0 },
    { dishId: 46, ingredientId: 14, quantity: 0 },
    { dishId: 46, ingredientId: 15, quantity: 0 },
    { dishId: 46, ingredientId: 16, quantity: 0 },
    { dishId: 47, ingredientId: 1, quantity: 0 },
    { dishId: 47, ingredientId: 2, quantity: 0 },
    { dishId: 47, ingredientId: 3, quantity: 0 },
    { dishId: 47, ingredientId: 4, quantity: 0 },
    { dishId: 47, ingredientId: 5, quantity: 11 },
    { dishId: 47, ingredientId: 6, quantity: 0 },
    { dishId: 47, ingredientId: 7, quantity: 0 },
    { dishId: 47, ingredientId: 8, quantity: 9 },
    { dishId: 47, ingredientId: 9, quantity: 7 },
    { dishId: 47, ingredientId: 10, quantity: 0 },
    { dishId: 47, ingredientId: 11, quantity: 0 },
    { dishId: 47, ingredientId: 12, quantity: 0 },
    { dishId: 47, ingredientId: 13, quantity: 8 },
    { dishId: 47, ingredientId: 14, quantity: 0 },
    { dishId: 47, ingredientId: 15, quantity: 0 },
    { dishId: 47, ingredientId: 16, quantity: 0 },
    { dishId: 48, ingredientId: 1, quantity: 0 },
    { dishId: 48, ingredientId: 2, quantity: 0 },
    { dishId: 48, ingredientId: 3, quantity: 0 },
    { dishId: 48, ingredientId: 4, quantity: 0 },
    { dishId: 48, ingredientId: 5, quantity: 12 },
    { dishId: 48, ingredientId: 6, quantity: 0 },
    { dishId: 48, ingredientId: 7, quantity: 0 },
    { dishId: 48, ingredientId: 8, quantity: 4 },
    { dishId: 48, ingredientId: 9, quantity: 0 },
    { dishId: 48, ingredientId: 10, quantity: 0 },
    { dishId: 48, ingredientId: 11, quantity: 0 },
    { dishId: 48, ingredientId: 12, quantity: 0 },
    { dishId: 48, ingredientId: 13, quantity: 0 },
    { dishId: 48, ingredientId: 14, quantity: 0 },
    { dishId: 48, ingredientId: 15, quantity: 0 },
    { dishId: 48, ingredientId: 16, quantity: 0 },
    { dishId: 49, ingredientId: 1, quantity: 0 },
    { dishId: 49, ingredientId: 2, quantity: 9 },
    { dishId: 49, ingredientId: 3, quantity: 0 },
    { dishId: 49, ingredientId: 4, quantity: 0 },
    { dishId: 49, ingredientId: 5, quantity: 15 },
    { dishId: 49, ingredientId: 6, quantity: 0 },
    { dishId: 49, ingredientId: 7, quantity: 0 },
    { dishId: 49, ingredientId: 8, quantity: 0 },
    { dishId: 49, ingredientId: 9, quantity: 0 },
    { dishId: 49, ingredientId: 10, quantity: 0 },
    { dishId: 49, ingredientId: 11, quantity: 11 },
    { dishId: 49, ingredientId: 12, quantity: 0 },
    { dishId: 49, ingredientId: 13, quantity: 0 },
    { dishId: 49, ingredientId: 14, quantity: 0 },
    { dishId: 49, ingredientId: 15, quantity: 0 },
    { dishId: 49, ingredientId: 16, quantity: 0 },
    { dishId: 50, ingredientId: 1, quantity: 0 },
    { dishId: 50, ingredientId: 2, quantity: 0 },
    { dishId: 50, ingredientId: 3, quantity: 0 },
    { dishId: 50, ingredientId: 4, quantity: 0 },
    { dishId: 50, ingredientId: 5, quantity: 0 },
    { dishId: 50, ingredientId: 6, quantity: 0 },
    { dishId: 50, ingredientId: 7, quantity: 0 },
    { dishId: 50, ingredientId: 8, quantity: 7 },
    { dishId: 50, ingredientId: 9, quantity: 9 },
    { dishId: 50, ingredientId: 10, quantity: 0 },
    { dishId: 50, ingredientId: 11, quantity: 0 },
    { dishId: 50, ingredientId: 12, quantity: 0 },
    { dishId: 50, ingredientId: 13, quantity: 8 },
    { dishId: 50, ingredientId: 14, quantity: 0 },
    { dishId: 50, ingredientId: 15, quantity: 0 },
    { dishId: 50, ingredientId: 16, quantity: 0 },
    { dishId: 51, ingredientId: 1, quantity: 0 },
    { dishId: 51, ingredientId: 2, quantity: 0 },
    { dishId: 51, ingredientId: 3, quantity: 0 },
    { dishId: 51, ingredientId: 4, quantity: 0 },
    { dishId: 51, ingredientId: 5, quantity: 0 },
    { dishId: 51, ingredientId: 6, quantity: 0 },
    { dishId: 51, ingredientId: 7, quantity: 0 },
    { dishId: 51, ingredientId: 8, quantity: 7 },
    { dishId: 51, ingredientId: 9, quantity: 0 },
    { dishId: 51, ingredientId: 10, quantity: 0 },
    { dishId: 51, ingredientId: 11, quantity: 0 },
    { dishId: 51, ingredientId: 12, quantity: 0 },
    { dishId: 51, ingredientId: 13, quantity: 0 },
    { dishId: 51, ingredientId: 14, quantity: 0 },
    { dishId: 51, ingredientId: 15, quantity: 0 },
    { dishId: 51, ingredientId: 16, quantity: 0 },
    { dishId: 52, ingredientId: 1, quantity: 0 },
    { dishId: 52, ingredientId: 2, quantity: 0 },
    { dishId: 52, ingredientId: 3, quantity: 8 },
    { dishId: 52, ingredientId: 4, quantity: 0 },
    { dishId: 52, ingredientId: 5, quantity: 0 },
    { dishId: 52, ingredientId: 6, quantity: 0 },
    { dishId: 52, ingredientId: 7, quantity: 0 },
    { dishId: 52, ingredientId: 8, quantity: 0 },
    { dishId: 52, ingredientId: 9, quantity: 0 },
    { dishId: 52, ingredientId: 10, quantity: 0 },
    { dishId: 52, ingredientId: 11, quantity: 0 },
    { dishId: 52, ingredientId: 12, quantity: 0 },
    { dishId: 52, ingredientId: 13, quantity: 0 },
    { dishId: 52, ingredientId: 14, quantity: 0 },
    { dishId: 52, ingredientId: 15, quantity: 7 },
    { dishId: 52, ingredientId: 16, quantity: 0 },
    { dishId: 53, ingredientId: 1, quantity: 0 },
    { dishId: 53, ingredientId: 2, quantity: 0 },
    { dishId: 53, ingredientId: 3, quantity: 0 },
    { dishId: 53, ingredientId: 4, quantity: 0 },
    { dishId: 53, ingredientId: 5, quantity: 0 },
    { dishId: 53, ingredientId: 6, quantity: 0 },
    { dishId: 53, ingredientId: 7, quantity: 0 },
    { dishId: 53, ingredientId: 8, quantity: 0 },
    { dishId: 53, ingredientId: 9, quantity: 0 },
    { dishId: 53, ingredientId: 10, quantity: 0 },
    { dishId: 53, ingredientId: 11, quantity: 0 },
    { dishId: 53, ingredientId: 12, quantity: 0 },
    { dishId: 53, ingredientId: 13, quantity: 8 },
    { dishId: 53, ingredientId: 14, quantity: 0 },
    { dishId: 53, ingredientId: 15, quantity: 15 },
    { dishId: 53, ingredientId: 16, quantity: 0 },
    { dishId: 54, ingredientId: 1, quantity: 0 },
    { dishId: 54, ingredientId: 2, quantity: 0 },
    { dishId: 54, ingredientId: 3, quantity: 0 },
    { dishId: 54, ingredientId: 4, quantity: 0 },
    { dishId: 54, ingredientId: 5, quantity: 7 },
    { dishId: 54, ingredientId: 6, quantity: 0 },
    { dishId: 54, ingredientId: 7, quantity: 0 },
    { dishId: 54, ingredientId: 8, quantity: 0 },
    { dishId: 54, ingredientId: 9, quantity: 0 },
    { dishId: 54, ingredientId: 10, quantity: 0 },
    { dishId: 54, ingredientId: 11, quantity: 0 },
    { dishId: 54, ingredientId: 12, quantity: 9 },
    { dishId: 54, ingredientId: 13, quantity: 0 },
    { dishId: 54, ingredientId: 14, quantity: 0 },
    { dishId: 54, ingredientId: 15, quantity: 0 },
    { dishId: 54, ingredientId: 16, quantity: 0 },
    { dishId: 55, ingredientId: 1, quantity: 0 },
    { dishId: 55, ingredientId: 2, quantity: 0 },
    { dishId: 55, ingredientId: 3, quantity: 0 },
    { dishId: 55, ingredientId: 4, quantity: 0 },
    { dishId: 55, ingredientId: 5, quantity: 0 },
    { dishId: 55, ingredientId: 6, quantity: 0 },
    { dishId: 55, ingredientId: 7, quantity: 0 },
    { dishId: 55, ingredientId: 8, quantity: 7 },
    { dishId: 55, ingredientId: 9, quantity: 6 },
    { dishId: 55, ingredientId: 10, quantity: 10 },
    { dishId: 55, ingredientId: 11, quantity: 0 },
    { dishId: 55, ingredientId: 12, quantity: 0 },
    { dishId: 55, ingredientId: 13, quantity: 0 },
    { dishId: 55, ingredientId: 14, quantity: 0 },
    { dishId: 55, ingredientId: 15, quantity: 0 },
    { dishId: 55, ingredientId: 16, quantity: 0 },
    { dishId: 56, ingredientId: 1, quantity: 0 },
    { dishId: 56, ingredientId: 2, quantity: 0 },
    { dishId: 56, ingredientId: 3, quantity: 0 },
    { dishId: 56, ingredientId: 4, quantity: 0 },
    { dishId: 56, ingredientId: 5, quantity: 0 },
    { dishId: 56, ingredientId: 6, quantity: 0 },
    { dishId: 56, ingredientId: 7, quantity: 0 },
    { dishId: 56, ingredientId: 8, quantity: 0 },
    { dishId: 56, ingredientId: 9, quantity: 0 },
    { dishId: 56, ingredientId: 10, quantity: 9 },
    { dishId: 56, ingredientId: 11, quantity: 0 },
    { dishId: 56, ingredientId: 12, quantity: 0 },
    { dishId: 56, ingredientId: 13, quantity: 7 },
    { dishId: 56, ingredientId: 14, quantity: 0 },
    { dishId: 56, ingredientId: 15, quantity: 6 },
    { dishId: 56, ingredientId: 16, quantity: 0 },
    { dishId: 57, ingredientId: 1, quantity: 0 },
    { dishId: 57, ingredientId: 2, quantity: 0 },
    { dishId: 57, ingredientId: 3, quantity: 0 },
    { dishId: 57, ingredientId: 4, quantity: 0 },
    { dishId: 57, ingredientId: 5, quantity: 0 },
    { dishId: 57, ingredientId: 6, quantity: 0 },
    { dishId: 57, ingredientId: 7, quantity: 0 },
    { dishId: 57, ingredientId: 8, quantity: 7 },
    { dishId: 57, ingredientId: 9, quantity: 0 },
    { dishId: 57, ingredientId: 10, quantity: 14 },
    { dishId: 57, ingredientId: 11, quantity: 0 },
    { dishId: 57, ingredientId: 12, quantity: 0 },
    { dishId: 57, ingredientId: 13, quantity: 0 },
    { dishId: 57, ingredientId: 14, quantity: 0 },
    { dishId: 57, ingredientId: 15, quantity: 0 },
    { dishId: 57, ingredientId: 16, quantity: 15 },
    { dishId: 58, ingredientId: 1, quantity: 0 },
    { dishId: 58, ingredientId: 2, quantity: 0 },
    { dishId: 58, ingredientId: 3, quantity: 0 },
    { dishId: 58, ingredientId: 4, quantity: 0 },
    { dishId: 58, ingredientId: 5, quantity: 20 },
    { dishId: 58, ingredientId: 6, quantity: 0 },
    { dishId: 58, ingredientId: 7, quantity: 0 },
    { dishId: 58, ingredientId: 8, quantity: 9 },
    { dishId: 58, ingredientId: 9, quantity: 0 },
    { dishId: 58, ingredientId: 10, quantity: 0 },
    { dishId: 58, ingredientId: 11, quantity: 20 },
    { dishId: 58, ingredientId: 12, quantity: 0 },
    { dishId: 58, ingredientId: 13, quantity: 0 },
    { dishId: 58, ingredientId: 14, quantity: 0 },
    { dishId: 58, ingredientId: 15, quantity: 0 },
    { dishId: 58, ingredientId: 16, quantity: 18 },
    { dishId: 59, ingredientId: 1, quantity: 0 },
    { dishId: 59, ingredientId: 2, quantity: 0 },
    { dishId: 59, ingredientId: 3, quantity: 0 },
    { dishId: 59, ingredientId: 4, quantity: 0 },
    { dishId: 59, ingredientId: 5, quantity: 11 },
    { dishId: 59, ingredientId: 6, quantity: 0 },
    { dishId: 59, ingredientId: 7, quantity: 0 },
    { dishId: 59, ingredientId: 8, quantity: 0 },
    { dishId: 59, ingredientId: 9, quantity: 0 },
    { dishId: 59, ingredientId: 10, quantity: 0 },
    { dishId: 59, ingredientId: 11, quantity: 0 },
    { dishId: 59, ingredientId: 12, quantity: 0 },
    { dishId: 59, ingredientId: 13, quantity: 11 },
    { dishId: 59, ingredientId: 14, quantity: 0 },
    { dishId: 59, ingredientId: 15, quantity: 0 },
    { dishId: 59, ingredientId: 16, quantity: 0 },
    { dishId: 60, ingredientId: 1, quantity: 0 },
    { dishId: 60, ingredientId: 2, quantity: 0 },
    { dishId: 60, ingredientId: 3, quantity: 25 },
    { dishId: 60, ingredientId: 4, quantity: 0 },
    { dishId: 60, ingredientId: 5, quantity: 0 },
    { dishId: 60, ingredientId: 6, quantity: 0 },
    { dishId: 60, ingredientId: 7, quantity: 0 },
    { dishId: 60, ingredientId: 8, quantity: 10 },
    { dishId: 60, ingredientId: 9, quantity: 17 },
    { dishId: 60, ingredientId: 10, quantity: 0 },
    { dishId: 60, ingredientId: 11, quantity: 0 },
    { dishId: 60, ingredientId: 12, quantity: 0 },
    { dishId: 60, ingredientId: 13, quantity: 25 },
    { dishId: 60, ingredientId: 14, quantity: 0 },
    { dishId: 60, ingredientId: 15, quantity: 0 },
    { dishId: 60, ingredientId: 16, quantity: 0 },
  ]);
}
